services:
  - type: web
    name: onestop-backend
    env: docker
    repo: https://github.com/Raven0770/OneStop-Tutor---Distraction-free-learning-environment
    dockerfilePath: ./backend/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: onestop-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: https://onestop-frontend.onrender.com

  - type: web
    name: onestop-frontend
    env: docker
    repo: https://github.com/Raven0770/OneStop-Tutor---Distraction-free-learning-environment
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://onestop-backend.onrender.com

  - type: pserv
    name: onestop-db
    env: docker
    plan: free